version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - ./db-data/solid-cms.menus.json:/src/data/solid-cms.menus.json

  mongo-import:
    image: mongo:latest
    volumes:
      - ./db-data/solid-cms.menus.json:/src/data/solid-cms.menus.json
    command: mongoimport --host mongodb --db solid-cms --collection menus --jsonArray --file /src/data/solid-cms.menus.json
    links:
      - mongodb

volumes:
  mongodb_data:
    driver: local
